### PR TITLE
Add CS21b from Brandeis University

### PR DESCRIPTION
**Pull request by robbyoconnor**
Structure and Interpretation of Computer Programs

### CODE REVIEW

**Comment by prakhar1989** [comment]
@robbyoconnor: Hey Robby, MIT 6.001 is a popular course which is based on the same book - SICP. The version on OCW even has videos by authors themselves - http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/video-lectures/. I feel the OCW course is more comprehensive than this one.  Let me know what you think.

**Comment by robbyoconnor** [comment]
Do you have that course listed? I'd be more than happy to close this but I also have this bias that there should be more variety

**Comment by robbyoconnor** [comment]
No issues :)

**Comment by prakhar1989** [comment]
:)

**Pull request closed without merging**
