### PR TITLE
Spacing, alphabetization (CS 4414), update to contribution guidelines

### PR DESCRIPTION
**Pull request by awelch83**

### CODE REVIEW

**Comment by prakhar1989** [comment]
Thanks Aaron!

**Comment by awelch83** [comment]
No problem :)

I'm still kind of new to github. If I'm making several changes to a file, as was the case here, is it better to roll them all into a single commit, or to make separate commits for spacing, alphabetization, etc, and then send them in a single pull request?

**Comment by prakhar1989** [comment]
There are no hard and fast rules, but typically logically related set of changes can (and should) be bundled in one commit. The (slight) problem in the above PR was that my earlier merge commits were sent again. Ideally, to get the latest set of changes from upstream, try doing `git pull --rebase` instead of a `git pull`. That would have just been one commit instead of 5 which it is showing now.

**Comment by awelch83** [comment]
Thanks - that was another question that I had - about those 4 other commits. I just wasn't sure how to ask it. I'm using a program called Tower 2 for mac right now, but maybe it'd be better to do what I need to do via the command line instead

**Pull request merged**
