### PR TITLE
Add University of Southern California CSCI 104 class.

### PR DESCRIPTION
**Pull request by robbyoconnor**
Add University of Southern California CSCI 104 class.

### CODE REVIEW

**Comment by prakhar1989** [comment]
Thanks for the PR Robby. Can you please send this as one commit instead of four? Thanks!

**Comment by awelch83** [comment]
@robbyoconnor Check out [this link](http://bit.ly/1qW0nJ7)

**Comment by robbyoconnor** [comment]
Fixed :)

**Comment by prakhar1989** [comment]
Thanks!

**Pull request merged**
