### PR TITLE
Add CS1410-20 at Utah

### PR DESCRIPTION
**Pull request by themattchan**

### CODE REVIEW

**Comment by prakhar1989** [comment]
Thanks for the PR, Matt. Could you please add links to assignments and lectures notes below the course description?

**Comment by themattchan** [comment]
Done!

**Comment by themattchan** [comment]
Idk if this should be under programming languages or intro though... it's a bit of both, but more intro

**Comment by prakhar1989** [comment]
Looks better in intro, IMO. Btw, do we need two links if they are some or would one do?

**Comment by themattchan** [comment]
Moved from PL -> intro

**Comment by themattchan** [comment]
They're two courses meant to be taken in succession, so I think two links would be better. (Also they're two different pages)

**Comment by prakhar1989** [comment]
Oh my bad! Thanks, Matt. I'll merge this right away :sparkles:

**Pull request merged**
