### PR TITLE
Added MIT Software Engineer interviewing course

### PR DESCRIPTION
**Pull request by cdipaolo96**
I added this course MIT ran for three weeks in their Independent Activities Period on 'hacking a google interview'. There aren't lectures but there are well written handouts that people can read through and sample questions.

### CODE REVIEW

**Comment by prakhar1989** [comment]
I've used these before and these are great! However, does it make more sense to add this as a supplemental material under any of the existing Algorithm courses? What do you think?

**Comment by cdipaolo96** [comment]
Yeah, it seems more relevant to the algorithms section. That said, if you put it under only one of the courses, people would probably miss it easier. You'd have to put it as like a sub-header or something under algorithms (like **Applications of Algorithms** or something), or have it as just like the first course in the algorithms section. Which do you think is best? I can just move it, close this pull request, and open a new one.

**Comment by prakhar1989** [comment]
Makes sense. How about you move it as a course under the algorithms section
and I'll merge it?

**Comment by cdipaolo96** [comment]
Ok, done! I have it moved on my fork so you can merge.

**Comment by prakhar1989** [comment]
Done!

**Pull request merged**
